CREATE USER IF NOT EXISTS 'kiwi_admin'@'%' IDENTIFIED BY 'kiwiKIWI';
ALTER USER 'kiwi_admin'@'%' IDENTIFIED BY 'kiwiKIWI';
GRANT ALL PRIVILEGES ON *.* TO 'kiwi_admin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
